---
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-etcd-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: milvus-standalone
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  embedEtcd.yaml: |
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://0.0.0.0:2379
    quota-backend-bytes: 4294967296
    auto-compaction-mode: revision
    auto-compaction-retention: '1000'
