---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: {{ .Release.Namespace }}
  labels:
    app: milvus-standalone
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-standalone
  template:
    metadata:
      labels:
        app: milvus-standalone
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9091"
        {{- toYaml $.Values.annotations | nindent 8 }}
    spec:
      runtimeClassName: nvidia
      containers:
        - name: milvus
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["milvus run standalone"]
          ports:
            - containerPort: 19530
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: milvus-env-config
          volumeMounts:
            - name: etcd-config
              mountPath: /milvus/configs/embedEtcd.yaml
              subPath: embedEtcd.yaml
            - name: user-config
              mountPath: /milvus/configs/user.yaml
              subPath: user.yaml
            - name: data
              mountPath: /var/lib/milvus
      volumes:
        - name: etcd-config
          configMap:
            name: milvus-etcd-config
        - name: user-config
          configMap:
              name: milvus-user-config
        - name: data
          hostPath:
            path: /opt/teknoir/milvus
            type: DirectoryOrCreate