---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: {{ .Release.Namespace }}
  labels:
    app: milvus-standalone
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  ports:
    - name: tcp-milvus
      port: 19530
      protocol: TCP
      targetPort: 19530
    - name: http-milvus
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: tcp-etcd
      port: 2379
      protocol: TCP
      targetPort: 2379

  selector:
    app: milvus-standalone
